import { StimBuff, EffectsHealthProperties, EffectsDamageProperties } from './types'

export interface StimTemplate {
  id: string
  name: string
  displayName: string
  parent: string
  handbookParentId: string
  backgroundColor: string
  weight: number
  width: number
  height: number
  stackMaxSize: number
  itemSound: string
  stimulatorBuffs: string
  medEffectType: string
  medUseTime: number
  maxHpResource: number
  hpResourceRate: number
  maxBodyPartsToHeal?: number
  prefab: string
  usePrefab: string
  customBuffs: StimBuff[]
  effectsHealth?: Record<string, EffectsHealthProperties>
  effectsDamage?: Record<string, EffectsDamageProperties>
  properties: Record<string, any>
}

export const STIM_TEMPLATES: StimTemplate[] = [
  {
    id: '544fb3f34bdc2d03748b456a',
    name: 'Morphine',
    displayName: 'Morphine',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsMorphine',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_morphine_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_morphine_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000001',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 305,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000002',
        buffType: 'EnergyRate',
        skillName: '',
        value: -10,
        delay: 0,
        duration: 305,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000003',
        buffType: 'HydrationRate',
        skillName: '',
        value: -15,
        delay: 0,
        duration: 305,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Morphine injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Morphine injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_morphine_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Morphine',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsMorphine',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_morphine_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5c10c8fd86f7743d7d706df3',
    name: 'Adrenaline',
    displayName: 'Adrenaline',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsAdrenaline',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000004',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 65,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000005',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 10,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000006',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 10,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000007',
        buffType: 'HealthRate',
        skillName: '',
        value: 4,
        delay: 1,
        duration: 15,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000008',
        buffType: 'SkillRate',
        skillName: 'StressResistance',
        value: -10,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000009',
        buffType: 'EnergyRate',
        skillName: '',
        value: -0.8,
        delay: 50,
        duration: 30,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000010',
        buffType: 'HydrationRate',
        skillName: '',
        value: -1,
        delay: 50,
        duration: 30,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Adrenaline injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Adrenaline injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Adrenaline',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsAdrenaline',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5c0e530286f7747fa1419862',
    name: 'Propital',
    displayName: 'Propital',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsPropital',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000011',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 245,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000012',
        buffType: 'SkillRate',
        skillName: 'Metabolism',
        value: 20,
        delay: 1,
        duration: 300,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000013',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: 20,
        delay: 1,
        duration: 300,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000014',
        buffType: 'SkillRate',
        skillName: 'Vitality',
        value: 20,
        delay: 1,
        duration: 300,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000015',
        buffType: 'HealthRate',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 300,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000016',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 270,
        duration: 30,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000017',
        buffType: 'QuantumTunnelling',
        skillName: '',
        value: 1,
        delay: 270,
        duration: 30,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Propital regenerative stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Propital regenerative stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Propital',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsPropital',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5c0e534186f7747fa1419867',
    name: 'eTG_c',
    displayName: 'eTG-c',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsETGChange',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-c_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-c_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000018',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 1,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000019',
        buffType: 'SkillRate',
        skillName: 'Metabolism',
        value: 20,
        delay: 1,
        duration: 90,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000020',
        buffType: 'SkillRate',
        skillName: 'Immunity',
        value: 20,
        delay: 1,
        duration: 90,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000021',
        buffType: 'HealthRate',
        skillName: '',
        value: 6.5,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000022',
        buffType: 'EnergyRate',
        skillName: '',
        value: 0.5,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000023',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: -5,
        delay: 65,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000024',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: -5,
        delay: 65,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000025',
        buffType: 'EnergyRate',
        skillName: '',
        value: -3,
        delay: 65,
        duration: 20,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'eTG-change regenerative stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'eTG-change regenerative stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-c_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'eTG-c',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsETGChange',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-c_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5fca138c2a7b221b2852a5c6',
    name: 'xTG_12',
    displayName: 'xTG-12',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'green',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsXTG12',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_xtg-12_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_xtg-12_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000026',
        buffType: 'Antidote',
        skillName: '',
        value: 1,
        delay: 6,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000027',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: -5,
        delay: 6,
        duration: 60,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'green',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'xTG-12 antidote injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'xTG-12 antidote injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_xtg-12_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'xTG-12',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsXTG12',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_xtg-12_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '637b6251104668754b72f8f9',
    name: 'Perfotoran',
    displayName: 'Perfotoran',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsPerfotoran',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000028',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000029',
        buffType: 'SkillRate',
        skillName: 'Metabolism',
        value: 5,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000030',
        buffType: 'HealthRate',
        skillName: '',
        value: 1.5,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000031',
        buffType: 'Antidote',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000032',
        buffType: 'RemoveAllBloodLosses',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000033',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: -15,
        delay: 60,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000034',
        buffType: 'EnergyRate',
        skillName: '',
        value: -1.1,
        delay: 60,
        duration: 60,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Perfotoran (Blue Blood) stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Perfotoran (Blue Blood) stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Perfotoran',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsPerfotoran',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed515f6915ec335206e4152',
    name: 'AHF1_M',
    displayName: 'AHF1-M',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsAHF1M',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000035',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: 5,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000036',
        buffType: 'RemoveAllBloodLosses',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000037',
        buffType: 'HydrationRate',
        skillName: '',
        value: -0.3,
        delay: 1,
        duration: 120,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'AHF1-M stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'AHF1-M stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'AHF1-M',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsAHF1M',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5c0e533786f7747fa23f4d47',
    name: 'Zagustin',
    displayName: 'Zagustin',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsZagustin',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000038',
        buffType: 'SkillRate',
        skillName: 'Vitality',
        value: 20,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000039',
        buffType: 'RemoveAllBloodLosses',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000040',
        buffType: 'SkillRate',
        skillName: 'Metabolism',
        value: -5,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000041',
        buffType: 'HydrationRate',
        skillName: '',
        value: -1.4,
        delay: 170,
        duration: 40,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000042',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 170,
        duration: 40,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Zagustin hemostatic drug injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Zagustin hemostatic drug injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Zagustin',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsZagustin',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '637b6179104668754b72f8f5',
    name: 'PNB',
    displayName: 'PNB',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsPNB',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_pnb_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_pnb_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000043',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 40,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000044',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 20,
        delay: 1,
        duration: 40,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000045',
        buffType: 'HealthRate',
        skillName: '',
        value: 3,
        delay: 1,
        duration: 40,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000046',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: -20,
        delay: 41,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000047',
        buffType: 'SkillRate',
        skillName: 'Vitality',
        value: -20,
        delay: 41,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000048',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 41,
        duration: 20,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'PNB (Product 16) stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'PNB (Product 16) stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_pnb_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'PNB',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsPNB',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_pnb_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed515ece452db0eb56fc028',
    name: 'P22',
    displayName: 'P22',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsP22',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000049',
        buffType: 'SkillRate',
        skillName: 'StressResistance',
        value: 30,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000050',
        buffType: 'SkillRate',
        skillName: 'Health',
        value: 30,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000051',
        buffType: 'SkillRate',
        skillName: 'Vitality',
        value: 30,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000052',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: -10,
        delay: 65,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000053',
        buffType: 'StaminaRate',
        skillName: '',
        value: -0.8,
        delay: 65,
        duration: 60,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'P22 (Product 22) stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'P22 (Product 22) stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'P22',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsP22',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed5160a87bb8443d10680b5',
    name: 'Meldonin',
    displayName: 'Meldonin',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsMeldonin',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_meldonin_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_meldonin_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000054',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 10,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000055',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 20,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000056',
        buffType: 'StaminaRate',
        skillName: '',
        value: 0.5,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000057',
        buffType: 'EnergyRate',
        skillName: '',
        value: -0.1,
        delay: 30,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000058',
        buffType: 'HydrationRate',
        skillName: '',
        value: -0.1,
        delay: 30,
        duration: 900,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Meldonin injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Meldonin injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_meldonin_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Meldonin',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsMeldonin',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_meldonin_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5c0e531286f7747fa54205c2',
    name: 'SJ1',
    displayName: 'SJ1',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsSJ1TGLabs',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000059',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 20,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000060',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 20,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000061',
        buffType: 'SkillRate',
        skillName: 'StressResistance',
        value: 20,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000062',
        buffType: 'EnergyRate',
        skillName: '',
        value: -0.25,
        delay: 100,
        duration: 200,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000063',
        buffType: 'HydrationRate',
        skillName: '',
        value: -0.3,
        delay: 100,
        duration: 200,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'SJ1 TGLabs combat stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'SJ1 TGLabs combat stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'SJ1',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsSJ1TGLabs',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed515e03a40a50460332579',
    name: 'L1',
    displayName: 'L1',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsL1',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000064',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 120,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000065',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 10,
        delay: 1,
        duration: 120,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000066',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 20,
        delay: 1,
        duration: 120,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000067',
        buffType: 'MaxStamina',
        skillName: '',
        value: 30,
        delay: 1,
        duration: 120,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000068',
        buffType: 'EnergyRate',
        skillName: '',
        value: -0.45,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000069',
        buffType: 'HydrationRate',
        skillName: '',
        value: -0.45,
        delay: 1,
        duration: 60,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'L1 (Norepinephrine) injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'L1 (Norepinephrine) injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'L1',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsL1',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5c0e531d86f7747fa23f4d42',
    name: 'SJ6',
    displayName: 'SJ6',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsSJ6TGLabs',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000070',
        buffType: 'MaxStamina',
        skillName: '',
        value: 30,
        delay: 1,
        duration: 240,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000071',
        buffType: 'StaminaRate',
        skillName: '',
        value: 2,
        delay: 1,
        duration: 240,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000072',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 200,
        duration: 40,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000073',
        buffType: 'QuantumTunnelling',
        skillName: '',
        value: 1,
        delay: 200,
        duration: 40,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'SJ6 TGLabs combat stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'SJ6 TGLabs combat stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'SJ6',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsSJ6TGLabs',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed515c8d380ab312177c0fa',
    name: '3__b_TG_',
    displayName: '3-(b-TG)',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'Buffs3bTG',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_3-(b-tg)_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_3-(b-tg)_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000074',
        buffType: 'SkillRate',
        skillName: 'Attention',
        value: 30,
        delay: 1,
        duration: 240,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000075',
        buffType: 'SkillRate',
        skillName: 'Perception',
        value: 30,
        delay: 1,
        duration: 240,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000076',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 10,
        delay: 1,
        duration: 240,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000077',
        buffType: 'StaminaRate',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 240,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000078',
        buffType: 'EnergyRate',
        skillName: '',
        value: -0.25,
        delay: 120,
        duration: 120,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000079',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 220,
        duration: 45,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: '3-(b-TG) stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: '3-(b-TG) stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_3-(b-tg)_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: '3-(b-TG)',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'Buffs3bTG',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_3-(b-tg)_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '66507eabf5ddb0818b085b68',
    name: '2A2__b_TG_',
    displayName: '2A2-(b-TG)',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'Buffs2A2bTG',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2-(b-tg)_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2-(b-tg)_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000080',
        buffType: 'SkillRate',
        skillName: 'Attention',
        value: 10,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000081',
        buffType: 'SkillRate',
        skillName: 'Perception',
        value: 10,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000082',
        buffType: 'WeightLimit',
        skillName: '',
        value: 15,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000083',
        buffType: 'HydrationRate',
        skillName: '',
        value: -0.1,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: '2A2-(b-TG) stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: '2A2-(b-TG) stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2-(b-tg)_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: '2A2-(b-TG)',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'Buffs2A2bTG',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2-(b-tg)_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '637b620db7afa97bfc3d7009',
    name: 'Trimadol',
    displayName: 'Trimadol',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsTrimadol',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000084',
        buffType: 'RemoveNegativeEffects',
        skillName: '',
        value: 1,
        delay: 0,
        duration: 185,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000085',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 10,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000086',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 10,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000087',
        buffType: 'SkillRate',
        skillName: 'Attention',
        value: 10,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000088',
        buffType: 'SkillRate',
        skillName: 'StressResistance',
        value: 10,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000089',
        buffType: 'MaxStamina',
        skillName: '',
        value: 10,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000090',
        buffType: 'StaminaRate',
        skillName: '',
        value: 3,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000091',
        buffType: 'EnergyRate',
        skillName: '',
        value: -0.5,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000092',
        buffType: 'HydrationRate',
        skillName: '',
        value: -0.5,
        delay: 1,
        duration: 180,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Trimadol stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Trimadol stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Trimadol',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsTrimadol',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed5166ad380ab312177c100',
    name: 'Obdolbos',
    displayName: 'Obdolbos',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'green',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsObdolbos',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000093',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 10,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000094',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 10,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000095',
        buffType: 'SkillRate',
        skillName: 'Intellect',
        value: 10,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000096',
        buffType: 'SkillRate',
        skillName: 'Attention',
        value: 10,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000097',
        buffType: 'SkillRate',
        skillName: 'StressResistance',
        value: 10,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000098',
        buffType: 'SkillRate',
        skillName: 'Charisma',
        value: 10,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000099',
        buffType: 'MaxStamina',
        skillName: '',
        value: 20,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000100',
        buffType: 'HealthRate',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000101',
        buffType: 'StaminaRate',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000102',
        buffType: 'WeightLimit',
        skillName: '',
        value: 0.1,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000103',
        buffType: 'HealthRate',
        skillName: '',
        value: -600,
        delay: 1,
        duration: 600,
        chance: 0.33,
        absoluteValue: true
      },
      {
        id: '000000000000000000000104',
        buffType: 'DamageModifier',
        skillName: '',
        value: 20,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000105',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000106',
        buffType: 'HydrationRate',
        skillName: '',
        value: -1,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      },
      {
        id: '000000000000000000000107',
        buffType: 'EnergyRate',
        skillName: '',
        value: -1,
        delay: 1,
        duration: 600,
        chance: 0.25,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'green',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Obdolbos cocktail injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Obdolbos cocktail injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Obdolbos',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsObdolbos',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '637b60c3b7afa97bfc3d7001',
    name: 'Dolbos_2',
    displayName: 'Dolbos 2',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'green',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsObdolbos2',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_dolbos2_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_dolbos2_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000108',
        buffType: 'SkillRate',
        skillName: 'Endurance',
        value: 20,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000109',
        buffType: 'SkillRate',
        skillName: 'Strength',
        value: 20,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000110',
        buffType: 'SkillRate',
        skillName: 'Attention',
        value: 20,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000111',
        buffType: 'SkillRate',
        skillName: 'Perception',
        value: 20,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000112',
        buffType: 'WeightLimit',
        skillName: '',
        value: 45,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000113',
        buffType: 'MaxStamina',
        skillName: '',
        value: -20,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000114',
        buffType: 'StaminaRate',
        skillName: '',
        value: -1,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000115',
        buffType: 'HealthRate',
        skillName: '',
        value: -1,
        delay: 1,
        duration: 1800,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'green',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'Obdolbos 2 cocktail injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'Obdolbos 2 cocktail injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_dolbos2_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'Dolbos 2',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsObdolbos2',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_dolbos2_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5ed51652f6c34d2cc26336a1',
    name: 'M_U_L_E_',
    displayName: 'M.U.L.E.',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'orange',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsMULE',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000116',
        buffType: 'WeightLimit',
        skillName: '',
        value: 50,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000117',
        buffType: 'HealthRate',
        skillName: '',
        value: -0.1,
        delay: 1,
        duration: 900,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'orange',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'M.U.L.E. stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'M.U.L.E. stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'M.U.L.E.',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsMULE',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '5fca13ca637ee0341a484f46',
    name: 'SJ9',
    displayName: 'SJ9',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsSJ9TGLabs',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000118',
        buffType: 'BodyTemperature',
        skillName: '',
        value: -7,
        delay: 6,
        duration: 300,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000119',
        buffType: 'SkillRate',
        skillName: 'Metabolism',
        value: -20,
        delay: 6,
        duration: 420,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000120',
        buffType: 'HealthRate',
        skillName: '',
        value: -0.1,
        delay: 6,
        duration: 420,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000121',
        buffType: 'HandsTremor',
        skillName: '',
        value: 1,
        delay: 6,
        duration: 420,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000122',
        buffType: 'Pain',
        skillName: '',
        value: 1,
        delay: 300,
        duration: 120,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'SJ9 TGLabs combat stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'SJ9 TGLabs combat stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'SJ9',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsSJ9TGLabs',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  },
  {
    id: '637b612fb7afa97bfc3d7005',
    name: 'SJ12',
    displayName: 'SJ12',
    parent: '5448f3a64bdc2d60728b456a',
    handbookParentId: '5b47574386f77428ca22b33a',
    backgroundColor: 'blue',
    weight: 0.05,
    width: 1,
    height: 1,
    stackMaxSize: 1,
    itemSound: 'med_stimulator',
    stimulatorBuffs: 'BuffsSJ12TGLabs',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    prefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_loot.bundle',
    usePrefab: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_container.bundle',
    customBuffs: [
      {
        id: '000000000000000000000123',
        buffType: 'SkillRate',
        skillName: 'Perception',
        value: 30,
        delay: 1,
        duration: 600,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000124',
        buffType: 'BodyTemperature',
        skillName: '',
        value: -4,
        delay: 1,
        duration: 600,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000125',
        buffType: 'EnergyRate',
        skillName: '',
        value: 0.05,
        delay: 1,
        duration: 600,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000126',
        buffType: 'HydrationRate',
        skillName: '',
        value: 0.05,
        delay: 1,
        duration: 600,
        chance: 1,
        absoluteValue: true
      },
      {
        id: '000000000000000000000127',
        buffType: 'BodyTemperature',
        skillName: '',
        value: 6,
        delay: 606,
        duration: 300,
        chance: 1,
        absoluteValue: true
      }
    ],
    properties: {
      AnimationVariantsNumber: 0,
      BackgroundColor: 'blue',
      BodyPartPriority: [],
      CanRequireOnRagfair: false,
      CanSellOnRagfair: true,
      ConflictingItems: [],
      Description: 'SJ12 TGLabs combat stimulant injector',
      DiscardLimit: 1,
      DiscardingBlock: false,
      DropSoundType: 'None',
      ExamineExperience: 100,
      ExamineTime: 1,
      ExaminedByDefault: false,
      ExtraSizeDown: 0,
      ExtraSizeForceAdd: false,
      ExtraSizeLeft: 0,
      ExtraSizeRight: 0,
      ExtraSizeUp: 0,
      Height: 1,
      HideEntrails: false,
      InsuranceDisabled: false,
      IsAlwaysAvailableForInsurance: false,
      IsLockedafterEquip: false,
      IsSecretExitRequirement: false,
      IsSpecialSlotOnly: false,
      IsUnbuyable: false,
      IsUndiscardable: false,
      IsUngivable: false,
      IsUnremovable: false,
      IsUnsaleable: false,
      ItemSound: 'med_stimulator',
      LeftHandItem: false,
      LootExperience: 10,
      MaxHpResource: 0,
      MergesWithChildren: false,
      MetascoreGroup: 'Utility',
      Name: 'SJ12 TGLabs combat stimulant injector',
      NotShownInSlot: false,
      Prefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_loot.bundle',
        rcid: ''
      },
      QuestItem: false,
      QuestStashMaxCount: 0,
      RagFairCommissionModifier: 1,
      RarityPvE: 'Superrare',
      RepairCost: 0,
      RepairSpeed: 0,
      ShortName: 'SJ12',
      StackMaxSize: 1,
      StackObjectsCount: 1,
      StimulatorBuffs: 'BuffsSJ12TGLabs',
      Unlootable: false,
      UnlootableFromSide: [],
      UnlootableFromSlot: 'FirstPrimaryWeapon',
      UsePrefab: {
        path: 'assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_container.bundle',
        rcid: ''
      },
      Weight: 0.05,
      Width: 1,
      effects_damage: [],
      effects_health: [],
      hpResourceRate: 0,
      medEffectType: 'duringUse',
      medUseTime: 2
    }
  }
]
