import { StimBuff, EffectsHealthProperties, EffectsDamageProperties } from './types'

export interface StimTemplate {
  id: string
  name: string
  displayName: string
  parent: string
  handbookParentId: string
  backgroundColor: string
  weight: number
  width: number
  height: number
  stackMaxSize: number
  itemSound: string
  stimulatorBuffs: string
  medEffectType: string
  medUseTime: number
  maxHpResource: number
  hpResourceRate: number
  maxBodyPartsToHeal?: number
  prefab: string
  usePrefab: string
  customBuffs: StimBuff[]
  effectsHealth: Record<string, EffectsHealthProperties>
  effectsDamage: Record<string, EffectsDamageProperties>
  properties: Record<string, any>
}

export const STIM_TEMPLATES: StimTemplate[] = [
  {
    "id": "66507eabf5ddb0818b085b68",
    "name": "2A2-(b-TG)",
    "displayName": "2A2-(b-TG)",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_2A2bTG",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2_b_tg_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2_b_tg_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Attention", "value": 10, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Perception", "value": 10, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "WeightLimit", "skillName": "", "value": 0.15, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": false}, {"id": "000000000000000000000004", "buffType": "HydrationRate", "skillName": "", "value": -0.1, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "2A2-(b-TG)",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2_b_tg_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "2A2-(b-TG)",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_2A2bTG",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_2a2_b_tg_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed515c8d380ab312177c0fa",
    "name": "3-(b-TG)",
    "displayName": "3-(b-TG)",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_3bTG",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_3btg_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_3btg_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Attention", "value": 30, "delay": 1, "duration": 240, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Perception", "value": 30, "delay": 1, "duration": 240, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Strength", "value": 10, "delay": 1, "duration": 240, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "StaminaRate", "skillName": "", "value": 1, "delay": 1, "duration": 240, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 220, "duration": 45, "chance": 1, "absoluteValue": false}, {"id": "000000000000000000000006", "buffType": "EnergyRate", "skillName": "", "value": -0.25, "delay": 120, "duration": 120, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "3-(b-TG)",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_3btg_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "3-(b-TG)",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_3bTG",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_3btg_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed515f6915ec335206e4152",
    "name": "AHF1-M",
    "displayName": "AHF1-M",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_AHF1M",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Health", "value": 5, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "RemoveAllBloodLosses", "skillName": "", "value": 0, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": false}, {"id": "000000000000000000000003", "buffType": "HydrationRate", "skillName": "", "value": -0.3, "delay": 1, "duration": 120, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"HeavyBleeding": {"delay": 0, "duration": 60, "fadeOut": 0}, "LightBleeding": {"delay": 0, "duration": 60, "fadeOut": 0}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "AHF1-M",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "AHF1-M",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_AHF1M",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_ahf1-m_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "HeavyBleeding": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        },
        "LightBleeding": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5c0e534186f7747fa1419867",
    "name": "eTG_change",
    "displayName": "eTG-change",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "BuffseTGchange",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-change_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-change_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "HealthRate", "skillName": "", "value": 6.5, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "EnergyRate", "skillName": "", "value": 0.5, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Metabolism", "value": 20, "delay": 1, "duration": 90, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Immunity", "value": 20, "delay": 1, "duration": 90, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "EnergyRate", "skillName": "", "value": -3, "delay": 65, "duration": 20, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000006", "buffType": "SkillRate", "skillName": "Endurance", "value": -5, "delay": 65, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000007", "buffType": "SkillRate", "skillName": "Health", "value": -5, "delay": 65, "duration": 60, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"Contusion": {"delay": 0, "duration": 0, "fadeOut": 0}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "eTG-change",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-change_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "eTG-change",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "BuffseTGchange",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_etg-change_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Contusion": {
          "delay": 0,
          "duration": 0,
          "fadeOut": 0
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed515e03a40a50460332579",
    "name": "L1",
    "displayName": "L1(Norepinephrine)",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_L1",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Endurance", "value": 10, "delay": 1, "duration": 120, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 20, "delay": 1, "duration": 120, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "MaxStamina", "skillName": "", "value": 30, "delay": 1, "duration": 120, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "HydrationRate", "skillName": "", "value": -0.45, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "EnergyRate", "skillName": "", "value": -0.45, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"Pain": {"delay": 0, "duration": 120, "fadeOut": 0}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "L1(Norepinephrine)",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "L1(Norepinephrine)",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_L1",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_l1_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Pain": {
          "delay": 0,
          "duration": 120,
          "fadeOut": 0
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed51652f6c34d2cc26336a1",
    "name": "M.U.L.E",
    "displayName": "M.U.L.E",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_MULE",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "WeightLimit", "skillName": "", "value": 0.5, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": false}, {"id": "000000000000000000000002", "buffType": "HealthRate", "skillName": "", "value": -0.1, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "M.U.L.E",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "M.U.L.E",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_MULE",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mule_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed5160a87bb8443d10680b5",
    "name": "Meldonin",
    "displayName": "Meldonin",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_Meldonin",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mildronate_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mildronate_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Strength", "value": 10, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Endurance", "value": 20, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "StaminaRate", "skillName": "", "value": 0.5, "delay": 1, "duration": 900, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "HydrationRate", "skillName": "", "value": -0.1, "delay": 30, "duration": 900, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "EnergyRate", "skillName": "", "value": -0.1, "delay": 30, "duration": 900, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Meldonin",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mildronate_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Meldonin",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_Meldonin",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_mildronate_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "637b620db7afa97bfc3d7009",
    "name": "Trimadol",
    "displayName": "Meldonin",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_Trimadol",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Endurance", "value": 10, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 10, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Attention", "value": 10, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "StressResistance", "value": 10, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "MaxStamina", "skillName": "", "value": 10, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000006", "buffType": "StaminaRate", "skillName": "", "value": 3, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000007", "buffType": "EnergyRate", "skillName": "", "value": -0.5, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000008", "buffType": "HydrationRate", "skillName": "", "value": -0.5, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"Contusion": {"delay": 0, "duration": 180, "fadeOut": 0}, "Pain": {"delay": 0, "duration": 180, "fadeOut": 5}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Meldonin",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Meldonin",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_Trimadol",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_trimadol_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Contusion": {
          "delay": 0,
          "duration": 180,
          "fadeOut": 0
        },
        "Pain": {
          "delay": 0,
          "duration": 180,
          "fadeOut": 5
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed5166ad380ab312177c100",
    "name": "Obdolbos",
    "displayName": "Obdolbos",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_Obdolbos",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Endurance", "value": 10, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 10, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Intellect", "value": 10, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Attention", "value": 10, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "SkillRate", "skillName": "StressResistance", "value": 10, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000006", "buffType": "SkillRate", "skillName": "Charisma", "value": 10, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000007", "buffType": "MaxStamina", "skillName": "", "value": 20, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000008", "buffType": "HealthRate", "skillName": "", "value": 1, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000009", "buffType": "StaminaRate", "skillName": "", "value": 1, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000010", "buffType": "WeightLimit", "skillName": "", "value": 0.1, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000011", "buffType": "DamageModifier", "skillName": "", "value": 0.2, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": false}, {"id": "000000000000000000000012", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": false}, {"id": "000000000000000000000013", "buffType": "HydrationRate", "skillName": "", "value": -1, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000014", "buffType": "EnergyRate", "skillName": "", "value": -1, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}, {"id": "000000000000000000000015", "buffType": "HealthRate", "skillName": "", "value": -600, "delay": 0, "duration": 600, "chance": 0.25, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Obdolbos",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Obdolbos",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_Obdolbos",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "637b60c3b7afa97bfc3d7001",
    "name": "Obdolbos2",
    "displayName": "Obdolbos",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_Obdolbos2",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos2_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos2_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Endurance", "value": 20, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 20, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Attention", "value": 20, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Perception", "value": 20, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "WeightLimit", "skillName": "", "value": 0.45, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": false}, {"id": "000000000000000000000006", "buffType": "MaxStamina", "skillName": "", "value": -20, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000007", "buffType": "StaminaRate", "skillName": "", "value": -1, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000008", "buffType": "HealthRate", "skillName": "", "value": -1, "delay": 0, "duration": 1800, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Obdolbos",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos2_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Obdolbos",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_Obdolbos2",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_obdolbos2_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5ed515ece452db0eb56fc028",
    "name": "P22",
    "displayName": "P22",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_P22",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "StressResistance", "value": 30, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Health", "value": 30, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Vitality", "value": 30, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Endurance", "value": -10, "delay": 65, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "StaminaRate", "skillName": "", "value": -0.8, "delay": 65, "duration": 60, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "P22",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "P22",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_P22",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_p22_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "637b6179104668754b72f8f5",
    "name": "PNB",
    "displayName": "P22",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_PNB",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_simulator_pnb_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_simulator_pnb_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "HealthRate", "skillName": "", "value": 3, "delay": 1, "duration": 40, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 20, "delay": 1, "duration": 40, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Health", "value": -20, "delay": 41, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Vitality", "value": -20, "delay": 41, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 41, "duration": 20, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"Contusion": {"delay": 0, "duration": 40, "fadeOut": 0}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "P22",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_simulator_pnb_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "P22",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_PNB",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_simulator_pnb_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Contusion": {
          "delay": 0,
          "duration": 40,
          "fadeOut": 0
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5c0e531286f7747fa54205c2",
    "name": "SJ1_TGLabs",
    "displayName": "SJ1 TGLabs",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "BuffsSJ1TGLabs",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Endurance", "value": 20, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 20, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "StressResistance", "value": 20, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "EnergyRate", "skillName": "", "value": -0.25, "delay": 100, "duration": 200, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "HydrationRate", "skillName": "", "value": -0.3, "delay": 100, "duration": 200, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "SJ1 TGLabs",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "SJ1 TGLabs",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "BuffsSJ1TGLabs",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj1_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5c0e531d86f7747fa23f4d42",
    "name": "SJ6_TGLabs",
    "displayName": "SJ6 TGLabs",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "BuffsSJ6TGLabs",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "MaxStamina", "skillName": "", "value": 30, "delay": 1, "duration": 240, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "StaminaRate", "skillName": "", "value": 2, "delay": 1, "duration": 240, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 200, "duration": 40, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "QuantumTunnelling", "skillName": "", "value": 0, "delay": 200, "duration": 40, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "SJ6 TGLabs",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "SJ6 TGLabs",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "BuffsSJ6TGLabs",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj6_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5fca13ca637ee0341a484f46",
    "name": "SJ9_TGLabs",
    "displayName": "SJ9 TGLabs",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_BodyTemperature",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_tglabs_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_tglabs_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "BodyTemperature", "skillName": "", "value": -7, "delay": 6, "duration": 300, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Metabolism", "value": -20, "delay": 6, "duration": 300, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "HealthRate", "skillName": "", "value": -0.1, "delay": 6, "duration": 420, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 6, "duration": 420, "chance": 1, "absoluteValue": false}, {"id": "000000000000000000000005", "buffType": "Pain", "skillName": "", "value": 0, "delay": 300, "duration": 120, "chance": 1, "absoluteValue": false}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "SJ9 TGLabs",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_tglabs_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "SJ9 TGLabs",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_BodyTemperature",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj9_tglabs_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "637b612fb7afa97bfc3d7005",
    "name": "SJ12_TGLabs",
    "displayName": "SJ9 TGLabs",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_SJ12_TGLabs",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_tglabs_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_tglabs_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "BodyTemperature", "skillName": "", "value": -4, "delay": 1, "duration": 600, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "EnergyRate", "skillName": "", "value": 0.05, "delay": 1, "duration": 600, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "HydrationRate", "skillName": "", "value": 0.05, "delay": 1, "duration": 600, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Perception", "value": 30, "delay": 1, "duration": 600, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "BodyTemperature", "skillName": "", "value": 6, "delay": 606, "duration": 300, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "SJ9 TGLabs",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_tglabs_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "SJ9 TGLabs",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_SJ12_TGLabs",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_sj12_tglabs_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5fca138c2a7b221b2852a5c6",
    "name": "x-TG-12_antidote",
    "displayName": "x-TG-12 antidote",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_Antidote",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_x-tg-12_antidote_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_x-tg-12_antidote_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "Antidote", "skillName": "", "value": 0, "delay": 6, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Health", "value": -5, "delay": 6, "duration": 60, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "x-TG-12 antidote",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_x-tg-12_antidote_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "x-TG-12 antidote",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_Antidote",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_x-tg-12_antidote_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": [],
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5c10c8fd86f7743d7d706df3",
    "name": "Adrenaline",
    "displayName": "Адреналин",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "BuffsAdrenaline",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Endurance", "value": 10, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Strength", "value": 10, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "StressResistance", "value": -10, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "HealthRate", "skillName": "", "value": 4, "delay": 1, "duration": 15, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "HydrationRate", "skillName": "", "value": -1, "delay": 50, "duration": 30, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000006", "buffType": "EnergyRate", "skillName": "", "value": -0.8, "delay": 50, "duration": 30, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"Contusion": {"delay": 0, "duration": 60, "fadeOut": 0}, "Pain": {"delay": 0, "duration": 60, "fadeOut": 5}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Адреналин",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Rare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Адреналин",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "BuffsAdrenaline",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_adrenaline_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Contusion": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        },
        "Pain": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 5
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5c0e533786f7747fa23f4d47",
    "name": "Zagustin",
    "displayName": "Загустин",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "BuffsZagustin",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Vitality", "value": 20, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Metabolism", "value": -5, "delay": 1, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "RemoveAllBloodLosses", "skillName": "", "value": 0, "delay": 0, "duration": 180, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 170, "duration": 40, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "HydrationRate", "skillName": "", "value": -1.4, "delay": 170, "duration": 40, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"HeavyBleeding": {"delay": 0, "duration": 180, "fadeOut": 0}, "LightBleeding": {"delay": 0, "duration": 180, "fadeOut": 0}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Загустин",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Загустин",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "BuffsZagustin",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_zagustin_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "HeavyBleeding": {
          "delay": 0,
          "duration": 180,
          "fadeOut": 0
        },
        "LightBleeding": {
          "delay": 0,
          "duration": 180,
          "fadeOut": 0
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "5c0e530286f7747fa1419862",
    "name": "Propital",
    "displayName": "Пропитал",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "BuffsPropital",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "HealthRate", "skillName": "", "value": 1, "delay": 1, "duration": 300, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "SkillRate", "skillName": "Metabolism", "value": 20, "delay": 1, "duration": 300, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "SkillRate", "skillName": "Health", "value": 20, "delay": 1, "duration": 300, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "SkillRate", "skillName": "Vitality", "value": 20, "delay": 1, "duration": 300, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "HandsTremor", "skillName": "", "value": 0, "delay": 270, "duration": 30, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000006", "buffType": "QuantumTunnelling", "skillName": "", "value": 0, "delay": 270, "duration": 30, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"Contusion": {"delay": 0, "duration": 240, "fadeOut": 0}, "Pain": {"delay": 0, "duration": 240, "fadeOut": 5}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Пропитал",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Пропитал",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "BuffsPropital",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_propital_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Contusion": {
          "delay": 0,
          "duration": 240,
          "fadeOut": 0
        },
        "Pain": {
          "delay": 0,
          "duration": 240,
          "fadeOut": 5
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "637b6251104668754b72f8f9",
    "name": "Perfotoran",
    "displayName": "Пропитал",
    "parent": "5448f3a64bdc2d60728b456a",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "Buffs_Perfotoran",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_container.bundle",
    "customBuffs": [{"id": "000000000000000000000001", "buffType": "SkillRate", "skillName": "Metabolism", "value": 5, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000002", "buffType": "Antidote", "skillName": "", "value": 0, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000003", "buffType": "RemoveAllBloodLosses", "skillName": "", "value": 0, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000004", "buffType": "HealthRate", "skillName": "", "value": 1.5, "delay": 1, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000005", "buffType": "SkillRate", "skillName": "Health", "value": -15, "delay": 60, "duration": 60, "chance": 1, "absoluteValue": true}, {"id": "000000000000000000000006", "buffType": "EnergyRate", "skillName": "", "value": -1.1, "delay": 60, "duration": 60, "chance": 1, "absoluteValue": true}],
    "effectsHealth": {},
    "effectsDamage": {"HeavyBleeding": {"delay": 0, "duration": 60, "fadeOut": 0}, "Intoxication": {"delay": 0, "duration": 60, "fadeOut": 0}, "LightBleeding": {"delay": 0, "duration": 60, "fadeOut": 0}, "RadExposure": {"delay": 0, "duration": 60, "fadeOut": 0}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": 2,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Пропитал",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Пропитал",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "Buffs_Perfotoran",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_stimulator_perfotoran_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "HeavyBleeding": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        },
        "Intoxication": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        },
        "LightBleeding": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        },
        "RadExposure": {
          "delay": 0,
          "duration": 60,
          "fadeOut": 0
        }
      },
      "effects_health": [],
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    },
  },
  {
    "id": "544fb3f34bdc2d03748b456a",
    "name": "morphine",
    "displayName": "Шприц с морфином",
    "parent": "5448f3a14bdc2d27728b4569",
    "handbookParentId": "5b47574386f77428ca22b33a",
    "backgroundColor": "orange",
    "weight": 0.05,
    "width": 1,
    "height": 1,
    "stackMaxSize": 1,
    "itemSound": "med_stimulator",
    "stimulatorBuffs": "",
    "medEffectType": "duringUse",
    "medUseTime": 2,
    "maxHpResource": 0,
    "hpResourceRate": 0,
    "prefab": "assets/content/weapons/usable_items/item_syringe/item_morphine_loot.bundle",
    "usePrefab": "assets/content/weapons/usable_items/item_syringe/item_syringe_container.bundle",
    "customBuffs": [],
    "effectsHealth": {"Energy": {"value": -10}, "Hydration": {"value": -15}},
    "effectsDamage": {"Contusion": {"delay": 0, "duration": 0, "fadeOut": 0}, "Pain": {"delay": 0, "duration": 300, "fadeOut": 5}},
    "properties": 
    {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "orange",
      "BodyPartPriority": [],
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "ConflictingItems": [],
      "Description": "",
      "DiscardLimit": -1,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 8,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "Height": 1,
      "HideEntrails": false,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_stimulator",
      "LeftHandItem": false,
      "LootExperience": 10,
      "MaxHpResource": 0,
      "MergesWithChildren": false,
      "MetascoreGroup": "Utility",
      "Name": "Шприц с морфином",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_morphine_loot.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Rare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Morphine",
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "StimulatorBuffs": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "assets/content/weapons/usable_items/item_syringe/item_syringe_container.bundle",
        "rcid": ""
      },
      "Weight": 0.05,
      "Width": 1,
      "effects_damage": {
        "Contusion": {
          "delay": 0,
          "duration": 0,
          "fadeOut": 0
        },
        "Pain": {
          "delay": 0,
          "duration": 300,
          "fadeOut": 5
        }
      },
      "effects_health": {
        "Energy": {
          "value": -10
        },
        "Hydration": {
          "value": -15
        }
      },
      "hpResourceRate": 0,
      "medEffectType": "duringUse",
      "medUseTime": 2
    }
  }
]
