export interface ContainerTemplate {
  id: string
  name: string
  displayName: string
  parent: string
  handbookParentId: string
  properties: Record<string, any>
}

export const CONTAINER_TEMPLATES: ContainerTemplate[] = [
  {
    "id": "5b7c710788a4506dec015957",
    "name": "item_container_junkbox",
    "displayName": "Lucky Scav Junk box",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "yellow",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": false,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "junkbox",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5b7c710788a4506dec015959",
          "_name": "main",
          "_parent": "5b7c710788a4506dec015957",
          "_props": {
            "cellsH": 14,
            "cellsV": 14,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448eb774bdc2d0a728b4567",
                  "5448ecbe4bdc2d60728b4568",
                  "5447e0e74bdc2d3c308b4567",
                  "6759673c76e93d8eb20b2080"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 4,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "junkbox",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_junkbox/item_container_junkbox.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "junkbox",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 15,
      "Width": 4
    }
  },
  {
    "id": "5c0a840b86f7742ffa4f2482",
    "name": "item_container_items_thicc",
    "displayName": "T H I C C item case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "yellow",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": false,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_items_thicc",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5c0a840b86f7742ffa4f2484",
          "_name": "main",
          "_parent": "5c0a840b86f7742ffa4f2482",
          "_props": {
            "cellsH": 14,
            "cellsV": 14,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448eb774bdc2d0a728b4567",
                  "543be5f84bdc2dd4348b456a",
                  "567143bf4bdc2d1a0f8b4567",
                  "5448fe124bdc2da5018b4567",
                  "5448e53e4bdc2d60728b4567",
                  "5448e5284bdc2dcb718b4567",
                  "60b0f6c058e0b0481a09ad11",
                  "5aafbde786f774389d0cbc0f",
                  "619cbf9e0a7c3a1a2731940a",
                  "5c093db286f7740a1b2617e3",
                  "5e2af55f86f7746d4159f07c",
                  "619cbf7d23893217ec30b689",
                  "59fafd4b86f7745ca07e1232",
                  "62a09d3bcf4a99369e262447",
                  "5d235bb686f77443f4331278",
                  "5c127c4486f7745625356c13",
                  "5aafbcd986f7745e590fff23",
                  "59fb016586f7746d0d4b423a",
                  "5c093e3486f77430cb02e593",
                  "590c60fc86f77412b13fddcf",
                  "5783c43d2459774bbe137486",
                  "5422acb9af1c889c16000029",
                  "543be6674bdc2df1348b4569",
                  "5448ecbe4bdc2d60728b4568",
                  "543be5e94bdc2df1348b4568",
                  "5447e1d04bdc2dff2f8b4567",
                  "567849dd4bdc2d150f8b456e",
                  "543be5664bdc2dd4348b4569",
                  "5f4fbaaca5573a5ac31db429",
                  "61605ddea09d851a0a0c1bbc",
                  "616eb7aea207f41933308f46",
                  "5991b51486f77447b112d44f",
                  "5ac78a9b86f7741cca0bbd8d",
                  "5b4391a586f7745321235ab2",
                  "5af056f186f7746da511291f",
                  "544fb5454bdc2df8738b456a",
                  "5661632d4bdc2d903d8b456b",
                  "543be6564bdc2df4348b4568",
                  "6759673c76e93d8eb20b2080",
                  "67d3ed3271c17ff82e0a5b0b"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 3,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_items_thicc",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_items_thicc/item_container_items_thicc.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_items_thicc",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 23,
      "Width": 5
    }
  },
  {
    "id": "5b6d9ce188a4501afc1b2b25",
    "name": "item_container_weaponcase_THICC",
    "displayName": "T H I C C Weapon case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "yellow",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": false,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Weaponcase thicc",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5b6d9ce188a4501afc1b2b27",
          "_name": "main",
          "_parent": "5b6d9ce188a4501afc1b2b25",
          "_props": {
            "cellsH": 6,
            "cellsV": 15,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448fe124bdc2da5018b4567",
                  "5422acb9af1c889c16000029",
                  "5485a8684bdc2da71d8b4567",
                  "543be5cb4bdc2deb348b4568"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "Weaponcase thicc",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_weapon_thicc/item_container_weapon_thicc.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Weaponcase thicc",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 18,
      "Width": 5
    }
  },
  {
    "id": "59fb042886f7746c5005a7b2",
    "name": "item_container_trackcase",
    "displayName": "Item case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Itemcase",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "59fb042886f7746c5005a7b3",
          "_name": "main",
          "_parent": "59fb042886f7746c5005a7b2",
          "_props": {
            "cellsH": 8,
            "cellsV": 8,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448eb774bdc2d0a728b4567",
                  "543be5f84bdc2dd4348b456a",
                  "5448fe124bdc2da5018b4567",
                  "5448e53e4bdc2d60728b4567",
                  "5448e5284bdc2dcb718b4567",
                  "60b0f6c058e0b0481a09ad11",
                  "5aafbde786f774389d0cbc0f",
                  "619cbf9e0a7c3a1a2731940a",
                  "5c093db286f7740a1b2617e3",
                  "5e2af55f86f7746d4159f07c",
                  "619cbf7d23893217ec30b689",
                  "59fafd4b86f7745ca07e1232",
                  "62a09d3bcf4a99369e262447",
                  "5d235bb686f77443f4331278",
                  "5c127c4486f7745625356c13",
                  "5aafbcd986f7745e590fff23",
                  "59fb016586f7746d0d4b423a",
                  "5c093e3486f77430cb02e593",
                  "590c60fc86f77412b13fddcf",
                  "5783c43d2459774bbe137486",
                  "5422acb9af1c889c16000029",
                  "543be6674bdc2df1348b4569",
                  "5448ecbe4bdc2d60728b4568",
                  "543be5e94bdc2df1348b4568",
                  "5447e1d04bdc2dff2f8b4567",
                  "567849dd4bdc2d150f8b456e",
                  "543be5664bdc2dd4348b4569",
                  "5f4fbaaca5573a5ac31db429",
                  "61605ddea09d851a0a0c1bbc",
                  "616eb7aea207f41933308f46",
                  "5991b51486f77447b112d44f",
                  "5ac78a9b86f7741cca0bbd8d",
                  "5b4391a586f7745321235ab2",
                  "5af056f186f7746da511291f",
                  "544fb5454bdc2df8738b456a",
                  "5661632d4bdc2d903d8b456b",
                  "543be6564bdc2df4348b4568",
                  "6759673c76e93d8eb20b2080",
                  "67d3ed3271c17ff82e0a5b0b"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 4,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "Itemcase",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_trackcase/item_container_trackcase.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Itemcase",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 7,
      "Width": 4
    }
  },
  {
    "id": "67600929bd0a0549d70993f6",
    "name": "item_container_plates_case",
    "displayName": "Ballistic plate case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "yellow",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_plates_case",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "67600929bd0a0549d70993f8",
          "_name": "main",
          "_parent": "67600929bd0a0549d70993f6",
          "_props": {
            "cellsH": 8,
            "cellsV": 12,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "644120aa86ffbe10ee032b6f"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_plates_case",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_plates_case/item_container_plates_case.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_plates_case",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 13,
      "Width": 4
    }
  },
  {
    "id": "59fb023c86f7746d0d4b423c",
    "name": "item_container_weaponcase",
    "displayName": "Weapon case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Weaponcase",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "59fb023c86f7746d0d4b423d",
          "_name": "main",
          "_parent": "59fb023c86f7746d0d4b423c",
          "_props": {
            "cellsH": 5,
            "cellsV": 10,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448fe124bdc2da5018b4567",
                  "5422acb9af1c889c16000029",
                  "5485a8684bdc2da71d8b4567",
                  "543be5cb4bdc2deb348b4568"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "Weaponcase",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_weaponcase/item_container_weaponcase.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Weaponcase",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 9,
      "Width": 5
    }
  },
  {
    "id": "66bc98a01a47be227a5e956e",
    "name": "item_container_streamer_case",
    "displayName": "Streamer item case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "violet",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": false,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Itemcase",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 100,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "66bc98a01a47be227a5e9570",
          "_name": "main",
          "_parent": "66bc98a01a47be227a5e956e",
          "_props": {
            "cellsH": 7,
            "cellsV": 11,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "62a09cfe4f842e1bd12da3e4",
                  "5bc9bdb8d4351e003562b8a1",
                  "5bc9bc53d4351e00367fbcee",
                  "66b37ea4c5d72b0277488439",
                  "5f745ee30acaeb0d490d8c5b",
                  "62a091170b9d3c46de5b6cf2",
                  "5e54f62086f774219b0f1937",
                  "66b37eb4acff495a29492407",
                  "5bc9b355d4351e6d1509862a",
                  "60b0f7057897d47c5b04ab94",
                  "5bc9c049d4351e44f824d360",
                  "5e54f6af86f7742199090bf3",
                  "5bc9be8fd4351e00334cae6e",
                  "62a08f4c4f842e1bd12d9d62",
                  "5bc9c377d4351e3bac12251b",
                  "66b37f114410565a8f6789e2",
                  "62a09e73af34e73a266d932a",
                  "62a09e974f842e1bd12da3f0",
                  "60b0f988c4449e4cb624c1da",
                  "62a09d79de7ac81993580530",
                  "62a09dd4621468534a797ac7",
                  "5e54f79686f7744022011103",
                  "5e54f76986f7740366043752",
                  "60b0f6c058e0b0481a09ad11",
                  "62a09d3bcf4a99369e262447",
                  "62a09e410b9d3c46de5b6e78",
                  "60b0f561c4449e4cb624c1d7",
                  "5bc9b9ecd4351e3bac122519",
                  "60b0f93284c20f0feb453da7",
                  "5bc9c29cd4351e003562b8a3",
                  "5bc9b156d4351e00367fbce9",
                  "5bc9c1e2d4351e00367fbcf0",
                  "62a09e08de7ac81993580532",
                  "5bd073a586f7747e6f135799",
                  "62a09ec84f842e1bd12da3f2",
                  "62a09cb7a04c0c5c6e0a84f8",
                  "5bc9b720d4351e450201234b",
                  "5fd8d28367cb5e077335170f",
                  "5bd073c986f7747f627e796c"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 3,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "Itemcase",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/location_objects/lootable/prefab/rand_loot_container_twitch_event.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Itemcase",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 7,
      "Width": 3
    }
  },
  {
    "id": "5aafbcd986f7745e590fff23",
    "name": "item_container_meds",
    "displayName": "Medicine case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": false,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "medscase",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5aafbcd986f7745e590fff25",
          "_name": "main",
          "_parent": "5aafbcd986f7745e590fff23",
          "_props": {
            "cellsH": 7,
            "cellsV": 7,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "57864c8c245977548867e7f1",
                  "543be5664bdc2dd4348b4569"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 3,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "medscase",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_meds/item_container_meds.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "medscase",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 16,
      "Width": 3
    }
  },
  {
    "id": "5e2af55f86f7746d4159f07c",
    "name": "item_container_grenadebox",
    "displayName": "Grenade case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_grenadebox",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5e2af55f86f7746d4159f07e",
          "_name": "main",
          "_parent": "5e2af55f86f7746d4159f07c",
          "_props": {
            "cellsH": 8,
            "cellsV": 8,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5e2af51086f7746d3f3c3402",
                  "5656eb674bdc2d35148b457c",
                  "5ede474b0c226a66f5402622",
                  "5ede475b549eed7c6d5c18fb",
                  "5ede4739e0350d05467f73e8",
                  "5f0c892565703e5c461894e9",
                  "5ede47405b097655935d7d16",
                  "5ede475339ee016e8c534742",
                  "5ede47641cf3836a88318df1",
                  "543be6564bdc2df4348b4568"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 3,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_metal",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_grenadebox",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_grenadebox/item_container_grenadebox.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_grenadebox",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 3,
      "Width": 3
    }
  },
  {
    "id": "5c093db286f7740a1b2617e3",
    "name": "item_container_food",
    "displayName": "Mr. Holodilnick thermal bag",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_food",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5c093db286f7740a1b2617e5",
          "_name": "main",
          "_parent": "5c093db286f7740a1b2617e3",
          "_props": {
            "cellsH": 8,
            "cellsV": 8,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5af0484c86f7740f02001f7f",
                  "5e54f6af86f7742199090bf3",
                  "5bc9be8fd4351e00334cae6e",
                  "543be6674bdc2df1348b4569",
                  "6389c6463485cf0eeb260715",
                  "67586af7036d7f3da60c3612",
                  "67586b7e49c2fa592e0d8ed9"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 3,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_food",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_food/item_container_food.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_food",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 12,
      "Width": 3
    }
  },
  {
    "id": "5c127c4486f7745625356c13",
    "name": "item_container_magbox",
    "displayName": "Magazine case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_magbox",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5c127c4486f7745625356c15",
          "_name": "main",
          "_parent": "5c127c4486f7745625356c13",
          "_props": {
            "cellsH": 7,
            "cellsV": 7,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448bc234bdc2d3c308b4569"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_metal",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_magbox",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_magbox/item_container_magbox.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_magbox",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 6,
      "Width": 3
    }
  },
  {
    "id": "59fb016586f7746d0d4b423a",
    "name": "item_container_money",
    "displayName": "Money case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Moneycase",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "59fb016586f7746d0d4b423b",
          "_name": "main",
          "_parent": "59fb016586f7746d0d4b423a",
          "_props": {
            "cellsH": 7,
            "cellsV": 7,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "59faff1d86f7746c51718c9c",
                  "5d235b4d86f7742e017bc88a",
                  "543be5dd4bdc2deb348b4569"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_metal",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "Moneycase",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_money/item_container_money.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Moneycase",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 5,
      "Width": 3
    }
  },
  {
    "id": "67d3ed3271c17ff82e0a5b0b",
    "name": "item_container_keys_case",
    "displayName": "Key case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_keys_case",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "67d3ed3271c17ff82e0a5b0d",
          "_name": "main",
          "_parent": "67d3ed3271c17ff82e0a5b0b",
          "_props": {
            "cellsH": 11,
            "cellsV": 7,
            "filters": [
              {
                "ExcludedFilter": [
                  "67ab3d4b83869afd170fdd3f",
                  "678fa929819ddc4c350c0317"
                ],
                "Filter": [
                  "543be5e94bdc2df1348b4568",
                  "59fafd4b86f7745ca07e1232",
                  "62a09d3bcf4a99369e262447",
                  "619cbf9e0a7c3a1a2731940a",
                  "67449b6c89d5e1ddc603f504"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_keys_case",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/barter/item_container_keys_case/item_container_keys_case.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_keys_case",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 4,
      "Width": 3
    }
  },
  {
    "id": "5aafbde786f774389d0cbc0f",
    "name": "item_container_ammo",
    "displayName": "Ammunition case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "ammocase",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5aafbde786f774389d0cbc11",
          "_name": "main",
          "_parent": "5aafbde786f774389d0cbc0f",
          "_props": {
            "cellsH": 7,
            "cellsV": 7,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5485a8684bdc2da71d8b4567",
                  "543be5cb4bdc2deb348b4568"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_metal",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "ammocase",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_ammo/item_container_ammo.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "ammocase",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 3,
      "Width": 2
    }
  },
  {
    "id": "567143bf4bdc2d1a0f8b4567",
    "name": "Suitcase",
    "displayName": "Pistol case",
    "parent": "5671435f4bdc2d96058b4569",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Pistol case",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "56f95c8ad2720bfa308b4581",
          "_name": "main",
          "_parent": "567143bf4bdc2d1a0f8b4567",
          "_props": {
            "cellsH": 4,
            "cellsV": 3,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5448bc234bdc2d3c308b4569",
                  "620109578d82e67e7911abf2",
                  "5447b5cf4bdc2d65278b4567",
                  "624c2e8614da335f1e034d8c",
                  "61a4c8884f95bc3b2c5dc96f",
                  "5485a8684bdc2da71d8b4567",
                  "543be5cb4bdc2deb348b4568",
                  "633ec7c2a6918cb895019c6c"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "KeyIds": [
        "5671446a4bdc2d97058b4569"
      ],
      "LeftHandItem": false,
      "LootExperience": 20,
      "MergesWithChildren": false,
      "Name": "Pistol case",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/pistol_case/item_container_pistol_case.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Rare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Pistol case",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.5,
      "Width": 2
    }
  },
  {
    "id": "590c60fc86f77412b13fddcf",
    "name": "item_info_docbag",
    "displayName": "Documents case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Docbag",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "590c60fc86f77412b13fddd0",
          "_name": "main",
          "_parent": "590c60fc86f77412b13fddcf",
          "_props": {
            "cellsH": 4,
            "cellsV": 4,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "59faff1d86f7746c51718c9c",
                  "5f745ee30acaeb0d490d8c5b",
                  "619cbf9e0a7c3a1a2731940a",
                  "5448ecbe4bdc2d60728b4568",
                  "543be5e94bdc2df1348b4568",
                  "567849dd4bdc2d150f8b456e",
                  "543be5dd4bdc2deb348b4569",
                  "67449b6c89d5e1ddc603f504",
                  "6759673c76e93d8eb20b2080"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 2,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "gear_generic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "Docbag",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/infosubject/item_info_docbag/item_info_docbag.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Docbag",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.82,
      "Width": 1
    }
  },
  {
    "id": "5d235bb686f77443f4331278",
    "name": "item_container_lopouch",
    "displayName": "S I C C organizational pouch",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_lopouch",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5d235bb686f77443f433127a",
          "_name": "main",
          "_parent": "5d235bb686f77443f4331278",
          "_props": {
            "cellsH": 5,
            "cellsV": 5,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "59faff1d86f7746c51718c9c",
                  "5f745ee30acaeb0d490d8c5b",
                  "5c1267ee86f77416ec610f72",
                  "5d235a5986f77443f6329bc6",
                  "59f32bb586f774757e1e8442",
                  "59f32c3b86f77472a31742f0",
                  "590c621186f774138d11ea29",
                  "543be5e94bdc2df1348b4568",
                  "543be5dd4bdc2deb348b4569",
                  "6662e9aca7e0b43baa3d5f74",
                  "6662e9cda7e0b43baa3d5f76",
                  "6662e9f37fa79a6d83730fa0",
                  "6662ea05f6259762c56f3189",
                  "67449b6c89d5e1ddc603f504",
                  "6759673c76e93d8eb20b2080",
                  "675dc9d37ae1a8792107ca96",
                  "675dcb0545b1a2d108011b2b",
                  "6764207f2fa5e32733055c4a",
                  "6764202ae307804338014c1a"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_pouch",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_lopouch",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_lopouch/item_container_lopouch.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Not_exist",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_lopouch",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.187,
      "Width": 2
    }
  },
  {
    "id": "59fafd4b86f7745ca07e1232",
    "name": "item_container_keybar",
    "displayName": "Key tool",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Key-tool",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 2,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "59fafd4b86f7745ca07e1233",
          "_name": "main",
          "_parent": "59fafd4b86f7745ca07e1232",
          "_props": {
            "cellsH": 4,
            "cellsV": 4,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5c99f98d86f7745c314214b3",
                  "67449b6c89d5e1ddc603f504"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "keys",
      "LeftHandItem": false,
      "LootExperience": 20,
      "MergesWithChildren": false,
      "Name": "Key-tool",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/barter/item_container_keybar/item_container_keybar.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Key-tool",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.2,
      "Width": 1
    }
  },
  {
    "id": "619cbf7d23893217ec30b689",
    "name": "item_container_injectorcase",
    "displayName": "Injector case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Key-tool",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 2,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "619cbf7d23893217ec30b68b",
          "_name": "main",
          "_parent": "619cbf7d23893217ec30b689",
          "_props": {
            "cellsH": 3,
            "cellsV": 3,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "544fb3f34bdc2d03748b456a",
                  "5448f3a64bdc2d60728b456a"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "med_medkit",
      "LeftHandItem": false,
      "LootExperience": 20,
      "MergesWithChildren": false,
      "Name": "Key-tool",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/barter/item_container_injectorcase/item_container_injectorcase.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Key-tool",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.35,
      "Width": 1
    }
  },
  {
    "id": "62a09d3bcf4a99369e262447",
    "name": "item_container_keychain",
    "displayName": "Gingy keychain",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "violet",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Key-tool",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 50,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "62a09d3bcf4a99369e262449",
          "_name": "main",
          "_parent": "62a09d3bcf4a99369e262447",
          "_props": {
            "cellsH": 2,
            "cellsV": 2,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5c99f98d86f7745c314214b3",
                  "67449b6c89d5e1ddc603f504"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "keys",
      "LeftHandItem": false,
      "LootExperience": 20,
      "MergesWithChildren": false,
      "Name": "Key-tool",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/barter/item_container_keychain/item_container_keychain.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Key-tool",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.015,
      "Width": 1
    }
  },
  {
    "id": "5783c43d2459774bbe137486",
    "name": "wallet",
    "displayName": "Simple wallet",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Empty Wallet",
      "DiscardLimit": 1,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 2,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "579604ac2459772e2a2a3d91",
          "_name": "main",
          "_parent": "5783c43d2459774bbe137486",
          "_props": {
            "cellsH": 2,
            "cellsV": 2,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5c164d2286f774194c5e69fa",
                  "543be5dd4bdc2deb348b4569"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "generic",
      "LeftHandItem": false,
      "LootExperience": 20,
      "MergesWithChildren": false,
      "Name": "Empty Wallet",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/barter/wallet/item_wallet.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Rare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Wallet",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.15,
      "Width": 1
    }
  },
  {
    "id": "60b0f6c058e0b0481a09ad11",
    "name": "item_barter_walletwz",
    "displayName": "WZ Wallet",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "violet",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "Empty Wallet",
      "DiscardLimit": 1,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 50,
      "ExamineTime": 1,
      "ExaminedByDefault": false,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "60b0f6c058e0b0481a09ad13",
          "_name": "main",
          "_parent": "60b0f6c058e0b0481a09ad11",
          "_props": {
            "cellsH": 2,
            "cellsV": 2,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "5c164d2286f774194c5e69fa",
                  "543be5dd4bdc2deb348b4569"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "generic",
      "LeftHandItem": false,
      "LootExperience": 20,
      "MergesWithChildren": false,
      "Name": "Empty Wallet",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/barter/item_barter_walletwz/item_barter_walletwz.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "Wallet",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.169,
      "Width": 1
    }
  },
  {
    "id": "5c093e3486f77430cb02e593",
    "name": "item_container_smallitems",
    "displayName": "Dogtag case",
    "parent": "5795f317245977243854e041",
    "handbookParentId": "5b5f6fa186f77409407a7eb7",
    "properties": {
      "AnimationVariantsNumber": 0,
      "BackgroundColor": "blue",
      "CanPutIntoDuringTheRaid": true,
      "CanRequireOnRagfair": false,
      "CanSellOnRagfair": true,
      "CantRemoveFromSlotsDuringRaid": [],
      "ConflictingItems": [],
      "Description": "item_container_smallitems",
      "DiscardLimit": 0,
      "DiscardingBlock": false,
      "DropSoundType": "None",
      "ExamineExperience": 10,
      "ExamineTime": 1,
      "ExaminedByDefault": true,
      "ExtraSizeDown": 0,
      "ExtraSizeForceAdd": false,
      "ExtraSizeLeft": 0,
      "ExtraSizeRight": 0,
      "ExtraSizeUp": 0,
      "ForbidMissingVitalParts": false,
      "ForbidNonEmptyContainers": false,
      "Grids": [
        {
          "_id": "5c093e3486f77430cb02e595",
          "_name": "main",
          "_parent": "5c093e3486f77430cb02e593",
          "_props": {
            "cellsH": 10,
            "cellsV": 10,
            "filters": [
              {
                "ExcludedFilter": [],
                "Filter": [
                  "59f32bb586f774757e1e8442",
                  "59f32c3b86f77472a31742f0",
                  "6662ea05f6259762c56f3189",
                  "6662e9f37fa79a6d83730fa0",
                  "6662e9cda7e0b43baa3d5f76",
                  "6662e9aca7e0b43baa3d5f74",
                  "675dc9d37ae1a8792107ca96",
                  "675dcb0545b1a2d108011b2b",
                  "6764207f2fa5e32733055c4a",
                  "6764202ae307804338014c1a"
                ]
              }
            ],
            "isSortingTable": false,
            "maxCount": 0,
            "maxWeight": 0,
            "minCount": 0
          },
          "_proto": "55d329c24bdc2d892f8b4567"
        }
      ],
      "Height": 1,
      "HideEntrails": true,
      "InsuranceDisabled": false,
      "IsAlwaysAvailableForInsurance": false,
      "IsLockedafterEquip": false,
      "IsSecretExitRequirement": false,
      "IsSpecialSlotOnly": false,
      "IsUnbuyable": false,
      "IsUndiscardable": false,
      "IsUngivable": false,
      "IsUnremovable": false,
      "IsUnsaleable": false,
      "ItemSound": "container_plastic",
      "LeftHandItem": false,
      "LootExperience": 30,
      "MergesWithChildren": false,
      "Name": "item_container_smallitems",
      "NotShownInSlot": false,
      "Prefab": {
        "path": "assets/content/items/containers/item_container_smallitems/item_container_smallitems.bundle",
        "rcid": ""
      },
      "QuestItem": false,
      "QuestStashMaxCount": 0,
      "RagFairCommissionModifier": 1,
      "RarityPvE": "Superrare",
      "RepairCost": 0,
      "RepairSpeed": 0,
      "ShortName": "item_container_smallitems",
      "Slots": [],
      "StackMaxSize": 1,
      "StackObjectsCount": 1,
      "TagColor": 0,
      "TagName": "",
      "Unlootable": false,
      "UnlootableFromSide": [],
      "UnlootableFromSlot": "FirstPrimaryWeapon",
      "UsePrefab": {
        "path": "",
        "rcid": ""
      },
      "Weight": 0.2,
      "Width": 1
    }
  }
]
