export interface BundleFile {
  name: string
  data: ArrayBuffer
}

export interface ItemPackDefinition {
  enabled: boolean
  name: string
  questItems: QuestItemDefinition[]
  keys: KeyDefinition[]
  containers: ContainerDefinition[]
  stims: StimDefinition[]
  medkits: MedKitDefinition[]
  traders: TraderDefinition[]
  bundles?: BundleFile[]
}

export interface ItemDefinition {
  id: string
  enabled: boolean
  baseTpl: string
  name: string
  shortName: string
  description: string
  weight: number
  backgroundColor?: string
  handbookPriceRoubles: number
  fleaPriceRoubles: number
  rarityPvE: string
  canSellOnRagfair: boolean
  customIcon?: string
}

export interface QuestItemDefinition extends ItemDefinition {
  stackMaxSize: number
  questIds: string[]
  properties: Record<string, any>
}

export interface KeyDefinition extends ItemDefinition {
  uses: number
  keyCategory: string
  doorIds: string[]
  properties: Record<string, any>
}

export interface ContainerDefinition extends ItemDefinition {
  parent: string
  handbookParentId: string
  properties: Record<string, any>
  safeContainerMode: 'all' | 'include' | 'exclude'
  safeContainerIds: string[]
}

export interface StimBuff {
  id: string
  buffType: string
  skillName: string
  value: number
  delay: number
  duration: number
  chance: number
  absoluteValue: boolean
  hydration?: number
  energy?: number
}

export interface EffectsHealthProperties {
  value?: number
  delay?: number
  duration?: number
}

export interface EffectsDamageProperties {
  value?: number
  delay?: number
  duration?: number
  fadeOut?: number
  cost?: number
  healthPenaltyMin?: number
  healthPenaltyMax?: number
}

export interface StimDefinition extends ItemDefinition {
  itemSound: string
  stimulatorBuffs: string
  medEffectType: string
  medUseTime: number
  maxHpResource: number
  hpResourceRate: number
  maxBodyPartsToHeal: number
  stackMaxSize: number
  width: number
  height: number
  customBuffs: StimBuff[]
  effectsHealth: Record<string, EffectsHealthProperties>
  effectsDamage: Record<string, EffectsDamageProperties>
  properties: Record<string, any>
}

export interface MedKitDefinition extends StimDefinition {}

export interface TraderItemEntry {
  itemId: string
  enabled: boolean
  priceRoubles: number
  loyaltyLevel: number
  stockCount: number
  buyRestrictionMax: number
  unlimitedStock: boolean
  unlimitedBuyRestriction: boolean
}

export interface TraderDefinition {
  traderId: string
  enabled: boolean
  entries: TraderItemEntry[]
}

export interface ValidationError {
  field: string
  message: string
}

export function generateMongoId(): string {
  const hex = '0123456789abcdef'
  let id = ''
  for (let i = 0; i < 24; i++) {
    id += hex[Math.floor(Math.random() * 16)]
  }
  return id
}

export function createDefaultQuestItem(): QuestItemDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New Quest Item',
    shortName: 'New Quest Item',
    description: 'A custom quest inventory item generated by ItemGen.',
    weight: 0.5,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Not_exist',
    canSellOnRagfair: false,
    stackMaxSize: 1,
    questIds: [],
    properties: {},
  }
}

export function createDefaultKey(): KeyDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New Key',
    shortName: 'New Key',
    description: 'A custom key generated by ItemGen.',
    weight: 0.01,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Common',
    canSellOnRagfair: true,
    uses: 40,
    keyCategory: '',
    doorIds: [],
    properties: {},
  }
}

export function createDefaultContainer(): ContainerDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New Container',
    shortName: 'New Container',
    description: 'A custom container generated by ItemGen.',
    weight: 0,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Not_exist',
    canSellOnRagfair: false,
    parent: '5795f317245977243854e041',
    handbookParentId: '5b5f6fa186f77409407a7eb7',
    properties: {},
    safeContainerMode: 'all',
    safeContainerIds: [],
  }
}

export const ITEM_PARENT_NAMES: Record<string, string> = {
  '5448ecbe4bdc2d60728b4568': 'Info',
  '57864a3d24597754843f8721': 'Jewelry',
  '5c99f98d86f7745c314214b3': 'KeyMechanical',
  '5c164d2286f774194c5e69fa': 'Keycard',
  '5448f3a64bdc2d60728b456a': 'Stimulator',
  '5447e1d04bdc2dff2f8b4567': 'Knife',
  '5447b6194bdc2d67278b4567': 'MarksmanRifle',
  '5448e54d4bdc2dcc718b4568': 'Armor',
  '5448e5284bdc2dcb718b4567': 'Vest',
  '5448e53e4bdc2d60728b4567': 'Backpack',
  '5448eb774bdc2d0a728b4567': 'BarterItem',
  '543be5e94bdc2df1348b4568': 'Key',
  '543be5cb4bdc2deb348b4568': 'AmmoBox',
  '5485a8684bdc2da71d8b4567': 'Ammo',
  '5422acb9af1c889c16000029': 'Weapon',
  '5448fe124bdc2d5018b4567': 'Mod',
  '5d650c3e815116009f6201d2': 'Fuel',
  '5448f39d4bdc2d0a728b4568': 'MedKit',
  '5448f3ac4bdc2dce718b4569': 'Medical',
  '5448e8d04bdc2ddf718b4569': 'Food',
  '57864c8c245977548867e7f1': 'MedicalSupplies',
  '543be6674bdc2df1348b4569': 'FoodDrink',
  '543be5664bdc2dd4348b4569': 'Meds',
  '57864ee62459775490116fc1': 'Battery',
  '5795f317245977243854e041': 'SimpleContainer',
  '5671435f4bdc2d96058b4569': 'LockableContainer',
  '57864e4c24597754843f8723': 'Lubricant',
  '57864ada245977548638de91': 'BuildingMaterial',
  '5661632d4bdc2d903d8b456b': 'StackableItem',
  '5447e0e74bdc2d3c308b4567': 'SpecItem',
  '567849dd4bdc2d150f8b456e': 'Map',
  '543be6564bdc2df4348b4568': 'ThrowWeap',
  '590c745b86f7743cc433c5f2': 'Other',
  '616eb7aea207f41933308f46': 'RepairKits',
  '57bef4c42459772e8d35a53b': 'ArmoredEquipment',
  '5a341c4086f77401f2541505': 'Headwear',
  '543be5dd4bdc2deb348b4569': 'Money',
  '6759673c76e93d8eb20b2080': 'Flyer',
  '644120aa86ffbe10ee032b6f': 'ArmorPlate',
}

export const VANILLA_TRADERS = [
  { id: '54cb50c76803fa8b248b4571', name: 'Prapor' },
  { id: '54cb57776803fa99248b456e', name: 'Therapist' },
  { id: '58330581ace78e27b8b10cee', name: 'Skier' },
  { id: '5935c25fb3acc3127c3d8cd9', name: 'Peacekeeper' },
  { id: '579dc571d53a0658a154fbec', name: 'Fence' },
  { id: '5a7c2eca46aef81a7ca2145d', name: 'Mechanic' },
  { id: '5ac3b934156ae10c4430e83c', name: 'Ragman' },
  { id: '5c0647fdd443bc2504c2d371', name: 'Jaeger' },
  { id: '638f541a29ffd1183d187f57', name: 'Caretaker' },
  { id: '656f0f98d80a697f855d34b1', name: 'BTR' },
  { id: '6617beeaa9cfa777ca915b7c', name: 'Arena' },
  { id: '6864e812f9fe664cb8b8e152', name: 'Storyteller' },
]

export const HANDBOOK_CATEGORY_NAMES: Record<string, string> = {
  '5b47574386f77428ca22b33f': 'Quest Items / Keys',
  '5b47574386f77428ca22b33e': 'Barter Items',
  '5b47574386f77428ca22b340': 'Containers',
  '5b47574386f77428ca22b341': 'Facecovers',
  '5b47574386f77428ca22b342': 'Headgear',
  '5b47574386f77428ca22b344': 'Body Armor',
  '5b47574386f77428ca22b345': 'Weapons',
  '5b47574386f77428ca22b346': 'Magazines',
  '5b47574386f77428ca22b347': 'Ammo',
}

export function getParentName(parentId: string): string {
  return ITEM_PARENT_NAMES[parentId] || parentId
}

export function getHandbookCategoryName(categoryId: string): string {
  return HANDBOOK_CATEGORY_NAMES[categoryId] || categoryId
}

export function createDefaultTraderEntry(itemId: string = ''): TraderItemEntry {
  return {
    itemId,
    enabled: true,
    priceRoubles: 0,
    loyaltyLevel: 1,
    stockCount: 200,
    buyRestrictionMax: 200,
    unlimitedStock: false,
    unlimitedBuyRestriction: false,
  }
}

export function createDefaultTraderDefinition(traderId: string = VANILLA_TRADERS[0].id): TraderDefinition {
  return {
    traderId,
    enabled: true,
    entries: [],
  }
}

export function createDefaultStimBuff(): StimBuff {
  return {
    id: generateMongoId(),
    buffType: 'SkillRate',
    skillName: 'Metabolism',
    value: 10,
    delay: 1,
    duration: 300,
    chance: 1,
    absoluteValue: true,
  }
}

export function createDefaultStim(): StimDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New Stim',
    shortName: 'New Stim',
    description: 'A custom stimulant injector generated by ItemGen.',
    weight: 0.05,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Superrare',
    canSellOnRagfair: true,
    itemSound: 'med_stimulator',
    stimulatorBuffs: '',
    medEffectType: 'duringUse',
    medUseTime: 2,
    maxHpResource: 0,
    hpResourceRate: 0,
    maxBodyPartsToHeal: 0,
    stackMaxSize: 1,
    width: 1,
    height: 1,
    customBuffs: [],
    effectsHealth: {},
    effectsDamage: {},
    properties: {},
  }
}

export function createDefaultMedkit(): MedKitDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New MedKit',
    shortName: 'MedKit',
    description: 'A custom medkit generated by ItemGen.',
    weight: 0.5,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Rare',
    canSellOnRagfair: true,
    itemSound: 'med_medkit',
    stimulatorBuffs: '',
    medEffectType: 'duringUse',
    medUseTime: 3,
    maxHpResource: 400,
    hpResourceRate: 85,
    maxBodyPartsToHeal: 0,
    stackMaxSize: 1,
    width: 1,
    height: 2,
    customBuffs: [],
    effectsHealth: {},
    effectsDamage: {},
    properties: {},
  }
}

export function createDefaultPack(): ItemPackDefinition {
  return {
    enabled: true,
    name: 'My Custom Items',
    questItems: [],
    keys: [],
    containers: [],
    stims: [],
    medkits: [],
    traders: VANILLA_TRADERS.map(t => createDefaultTraderDefinition(t.id)),
    bundles: [],
  }
}
