export interface ItemPackDefinition {
  enabled: boolean
  name: string
  questItems: QuestItemDefinition[]
  keys: KeyDefinition[]
}

export interface ItemDefinition {
  id: string
  enabled: boolean
  baseTpl: string
  name: string
  shortName: string
  description: string
  weight: number
  backgroundColor?: string
  handbookPriceRoubles: number
  fleaPriceRoubles: number
  rarityPvE: string
  canSellOnRagfair: boolean
  customIcon?: string
  customModel?: string
}

export interface QuestItemDefinition extends ItemDefinition {
  stackMaxSize: number
  questIds: string[]
}

export interface KeyDefinition extends ItemDefinition {
  uses: number
  keyCategory: string
  doorIds: string[]
}

export interface ValidationError {
  field: string
  message: string
}

export function generateMongoId(): string {
  const hex = '0123456789abcdef'
  let id = ''
  for (let i = 0; i < 24; i++) {
    id += hex[Math.floor(Math.random() * 16)]
  }
  return id
}

export function createDefaultQuestItem(): QuestItemDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New Quest Item',
    shortName: 'New Quest Item',
    description: 'A custom quest inventory item generated by ItemGen.',
    weight: 0.5,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Not_exist',
    canSellOnRagfair: true,
    stackMaxSize: 1,
    questIds: [],
  }
}

export function createDefaultKey(): KeyDefinition {
  return {
    id: generateMongoId(),
    enabled: true,
    baseTpl: '',
    name: 'New Key',
    shortName: 'New Key',
    description: 'A custom key generated by ItemGen.',
    weight: 0.01,
    handbookPriceRoubles: 0,
    fleaPriceRoubles: 0,
    rarityPvE: 'Common',
    canSellOnRagfair: true,
    uses: 40,
    keyCategory: '',
    doorIds: [],
  }
}

export const ITEM_PARENT_NAMES: Record<string, string> = {
  '5448ecbe4bdc2d60728b4568': 'Info',
  '57864a3d24597754843f8721': 'Jewelry',
  '5c99f98d86f7745c314214b3': 'KeyMechanical',
  '5c164d2286f774194c5e69fa': 'Keycard',
  '5448f3a64bdc2d60728b456a': 'Stimulator',
  '5447e1d04bdc2dff2f8b4567': 'Knife',
  '5447b6194bdc2d67278b4567': 'MarksmanRifle',
  '5448e54d4bdc2dcc718b4568': 'Armor',
  '5448e5284bdc2dcb718b4567': 'Vest',
  '5448e53e4bdc2d60728b4567': 'Backpack',
  '5448eb774bdc2d0a728b4567': 'BarterItem',
  '543be5e94bdc2df1348b4568': 'Key',
  '543be5cb4bdc2deb348b4568': 'AmmoBox',
  '5485a8684bdc2da71d8b4567': 'Ammo',
  '5422acb9af1c889c16000029': 'Weapon',
  '5448fe124bdc2d5018b4567': 'Mod',
  '5d650c3e815116009f6201d2': 'Fuel',
  '5448f39d4bdc2d0a728b4568': 'MedKit',
  '5448f3ac4bdc2dce718b4569': 'Medical',
  '5448e8d04bdc2ddf718b4569': 'Food',
  '57864c8c245977548867e7f1': 'MedicalSupplies',
  '543be6674bdc2df1348b4569': 'FoodDrink',
  '543be5664bdc2dd4348b4569': 'Meds',
  '57864ee62459775490116fc1': 'Battery',
  '5795f317245977243854e041': 'SimpleContainer',
  '5671435f4bdc2d96058b4569': 'LockableContainer',
  '57864e4c24597754843f8723': 'Lubricant',
  '57864ada245977548638de91': 'BuildingMaterial',
  '5661632d4bdc2d903d8b456b': 'StackableItem',
  '5447e0e74bdc2d3c308b4567': 'SpecItem',
  '567849dd4bdc2d150f8b456e': 'Map',
  '543be6564bdc2df4348b4568': 'ThrowWeap',
  '590c745b86f7743cc433c5f2': 'Other',
  '616eb7aea207f41933308f46': 'RepairKits',
  '57bef4c42459772e8d35a53b': 'ArmoredEquipment',
  '5a341c4086f77401f2541505': 'Headwear',
  '543be5dd4bdc2deb348b4569': 'Money',
  '6759673c76e93d8eb20b2080': 'Flyer',
}

export const HANDBOOK_CATEGORY_NAMES: Record<string, string> = {
  '5b47574386f77428ca22b33f': 'Quest Items / Keys',
  '5b47574386f77428ca22b33e': 'Barter Items',
  '5b47574386f77428ca22b340': 'Containers',
  '5b47574386f77428ca22b341': 'Facecovers',
  '5b47574386f77428ca22b342': 'Headgear',
  '5b47574386f77428ca22b344': 'Body Armor',
  '5b47574386f77428ca22b345': 'Weapons',
  '5b47574386f77428ca22b346': 'Magazines',
  '5b47574386f77428ca22b347': 'Ammo',
}

export function getParentName(parentId: string): string {
  return ITEM_PARENT_NAMES[parentId] || parentId
}

export function getHandbookCategoryName(categoryId: string): string {
  return HANDBOOK_CATEGORY_NAMES[categoryId] || categoryId
}

export function createDefaultPack(): ItemPackDefinition {
  return {
    enabled: true,
    name: 'My Custom Items',
    questItems: [createDefaultQuestItem()],
    keys: [],
  }
}
